# Generated by Django 4.1.4 on 2023-01-07 18:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
