# Generated by Django 4.1.4 on 2023-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карти'},
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.JSONField(verbose_name='JSON карти'),
        ),
        migrations.AlterField(
            model_name='map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата останньої зміни'),
        ),
    ]
