# Generated by Django 4.1.4 on 2023-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=320, verbose_name='Фраза')),
                ('priority', models.IntegerField(default=0, max_length=100, verbose_name='Пріоритет')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фрази',
            },
        ),
    ]
