# Generated by Django 4.1.4 on 2023-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='phrase',
            field=models.CharField(max_length=320, unique=True, verbose_name='Фраза'),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Пріоритет'),
        ),
    ]
